"""Batch inference pipeline for the Graduate Admissions project.

The pipeline loads the immutable fitted Pipeline artifact, reads new
applicant data from a file, validates it against the canonical feature
schema, and persists the raw model predictions.

Transformation contract (Issue #34)
------------------------------------

- The artifact contains the complete preprocessing (imputation, encoding,
  scaling): predictions are generated by calling ``predict`` on the
  loaded Pipeline, never by refitting or rebuilding preprocessing by
  hand.
- The model artifact is only ever loaded read-only; it is never
  modified, refit or re-serialized.
- New data is expected to contain exactly the canonical feature columns
  (no target). Missing values are allowed and are handled by the
  artifact's imputers.
- Predictions are raw regression estimates: they are not clipped,
  calibrated or converted to percentages.

Autonomous execution
--------------------

Run from the repository root:

    uv run python src/pipelines/inference_pipeline/inference_pipeline.py

An optional positional argument overrides the new-data input file.
"""

from __future__ import annotations

import sys
from collections.abc import Sequence
from pathlib import Path
from typing import Protocol

import numpy as np
import pandas as pd

_SRC_DIR = Path(__file__).resolve().parents[2]
if str(_SRC_DIR) not in sys.path:
    sys.path.insert(0, str(_SRC_DIR))

_REPOSITORY_ROOT = _SRC_DIR.parent

from pipelines.feature_pipeline.feature_pipeline import (  # noqa: E402
    CATEGORICAL_DOMAINS,
    CONTINUOUS_RANGES,
    FEATURE_COLUMNS,
)
from pipelines.inference_pipeline.inference import (  # noqa: E402
    default_model_path,
    load_model,
)

NEW_DATA_FILENAME = "new_applicants.csv"
PREDICTIONS_FILENAME = "admission_predictions.csv"
PREDICTION_COLUMN = "predicted_chance_of_admit"

OFFENDING_VALUE_SAMPLE_LIMIT = 5

FEATURE_CONTINUOUS_RANGES: dict[str, tuple[float, float]] = {
    column: CONTINUOUS_RANGES[column] for column in FEATURE_COLUMNS if column in CONTINUOUS_RANGES
}


class BatchPredictivePipeline(Protocol):
    """Protocol for the fitted Pipeline operation used by batch inference."""

    def predict(self, features: pd.DataFrame) -> Sequence[float]:
        """Return predictions for the provided feature rows."""


class InferenceInputValidationError(ValueError):
    """Raised when the new data file fails the inference schema checks."""


def default_new_data_path() -> Path:
    """Return the repository-relative path of the new-applicants input file."""
    return _REPOSITORY_ROOT / "data" / "05_model_input" / NEW_DATA_FILENAME


def default_predictions_output_path() -> Path:
    """Return the repository-relative path of the persisted predictions."""
    return _REPOSITORY_ROOT / "data" / "07_model_output" / PREDICTIONS_FILENAME


def read_new_data(input_path: Path) -> pd.DataFrame:
    """Read the new-applicants CSV and strip its column names."""
    if not input_path.is_file():
        raise FileNotFoundError(f"New data file not found: {input_path}")

    new_data = pd.read_csv(input_path)
    new_data.columns = new_data.columns.str.strip()
    return new_data


def _check_schema(new_data: pd.DataFrame) -> list[str]:
    """Return failures about missing or unexpected feature columns."""
    expected_columns = list(FEATURE_COLUMNS)
    actual_columns = list(new_data.columns)
    missing_columns = [column for column in expected_columns if column not in actual_columns]
    unexpected_columns = [column for column in actual_columns if column not in expected_columns]
    if missing_columns or unexpected_columns:
        details = []
        if missing_columns:
            details.append(f"missing columns: {missing_columns}")
        if unexpected_columns:
            details.append(f"unexpected columns: {unexpected_columns}")
        return ["Schema: " + "; ".join(details) + "."]
    return []


def _check_dtypes(new_data: pd.DataFrame) -> list[str]:
    """Return failures about non-numeric feature columns."""
    failures: list[str] = []
    for column in FEATURE_COLUMNS:
        if column in new_data.columns and not pd.api.types.is_numeric_dtype(new_data[column].dtype):
            failures.append(f"{column}: expected numeric dtype, found {new_data[column].dtype}.")
    return failures


def _check_values(new_data: pd.DataFrame) -> list[str]:
    """Return failures about non-finite, out-of-range or out-of-domain values.

    Missing values are skipped: the artifact's imputers handle them.
    Columns whose dtype violates the contract are skipped too: their
    failure was already reported by :func:`_check_dtypes`.
    """
    failures: list[str] = []
    for column in FEATURE_COLUMNS:
        if column not in new_data.columns:
            continue
        if not pd.api.types.is_numeric_dtype(new_data[column].dtype):
            continue
        values = new_data[column].dropna()
        if values.empty:
            continue
        if not np.isfinite(values).all():
            failures.append(f"{column}: found non-finite values.")
            continue
        if column in FEATURE_CONTINUOUS_RANGES:
            lower_bound, upper_bound = FEATURE_CONTINUOUS_RANGES[column]
            outside = values[(values < lower_bound) | (values > upper_bound)]
            if not outside.empty:
                sample = sorted(set(outside.tolist()))[:OFFENDING_VALUE_SAMPLE_LIMIT]
                failures.append(
                    f"{column}: values {sample} outside range [{lower_bound:g}, {upper_bound:g}]."
                )
        if column in CATEGORICAL_DOMAINS:
            allowed_categories = CATEGORICAL_DOMAINS[column]
            outside = values[~values.isin(allowed_categories)]
            if not outside.empty:
                sample = sorted(set(outside.tolist()))[:OFFENDING_VALUE_SAMPLE_LIMIT]
                failures.append(
                    f"{column}: values {sample} outside allowed categories "
                    f"{sorted(allowed_categories)}."
                )
    return failures


def _check_non_empty(new_data: pd.DataFrame) -> list[str]:
    """Return failures about an empty input frame."""
    if new_data.empty:
        return ["Integrity: new data frame is empty."]
    return []


def validate_inference_input(new_data: pd.DataFrame) -> None:
    """Validate the new-data schema and domain rules; raise on any failure.

    All failures are collected so one call reports every issue. The
    function never mutates its input.
    """
    failures = [
        *_check_schema(new_data),
        *_check_dtypes(new_data),
        *_check_values(new_data),
        *_check_non_empty(new_data),
    ]
    if failures:
        header = f"Inference input validation failed with {len(failures)} issue(s):"
        details = "\n".join(f"- {failure}" for failure in failures)
        raise InferenceInputValidationError(f"{header}\n{details}")


def generate_predictions(
    model: BatchPredictivePipeline,
    new_data: pd.DataFrame,
) -> pd.Series:
    """Return the raw predictions in input order.

    The frame is reordered to the canonical feature order and the loaded
    Pipeline applies the training preprocessing internally.
    """
    ordered_features = new_data.loc[:, list(FEATURE_COLUMNS)]
    predictions = model.predict(ordered_features)
    return pd.Series(predictions, index=new_data.index, name=PREDICTION_COLUMN)


def persist_predictions(
    new_data: pd.DataFrame,
    predictions: pd.Series,
    output_path: Path,
) -> Path:
    """Persist the input rows plus their predictions as CSV and return the path."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_frame = new_data.assign(**{PREDICTION_COLUMN: predictions})
    output_frame.to_csv(output_path, index=False)
    return output_path


def run_inference_pipeline(
    input_path: Path | None = None,
    model_path: Path | None = None,
    output_path: Path | None = None,
) -> Path:
    """Run batch inference end to end and return the predictions path.

    Data flow:

    1. read the new-applicants file;
    2. validate it against the canonical feature schema;
    3. load the immutable fitted Pipeline artifact read-only;
    4. generate raw predictions through the artifact;
    5. persist the input rows plus predictions to the output layer.
    """
    new_data = read_new_data(input_path or default_new_data_path())
    validate_inference_input(new_data)
    model = load_model(model_path)
    predictions = generate_predictions(model, new_data)
    return persist_predictions(
        new_data,
        predictions,
        output_path or default_predictions_output_path(),
    )


def main() -> None:
    """Run batch inference with the repository defaults from the CLI.

    An optional positional argument overrides the new-data input file.
    """
    input_path = Path(sys.argv[1]) if len(sys.argv) > 1 else default_new_data_path()
    model_path = default_model_path()
    output_path = run_inference_pipeline(input_path=input_path, model_path=model_path)

    predictions_frame = pd.read_csv(output_path)
    print(f"Model artifact: {model_path}")
    print(f"New data file: {input_path}")
    print(f"Predictions generated: {len(predictions_frame)} row(s)")
    print(f"Predictions persisted to: {output_path}")
    sample_predictions = predictions_frame[PREDICTION_COLUMN].head(5).round(6)
    print(f"Sample predictions:\n{sample_predictions.to_string(index=False)}")


if __name__ == "__main__":
    main()
